[package]
name = "snake"
version = "0.1.0"
authors = ["Redfox <vitor_pereira.2013@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
oorandom = "11.1.3"
getrandom = "0.2.2"
glam = "0.13.1"